
exports.querySelector = {
    "chaveNFe": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(9) > td > table > table > tbody > tr > td:nth-child(1) > span > span.linha",
    "numero": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(9) > td > table > table > tbody > tr > td:nth-child(2) > span.linha",
    "versaoXML": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(9) > td > table > table > tbody > tr > td:nth-child(3) > span.linha",
    "nfe" : {
        "modelo": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(1) > div > table:nth-child(2) > tbody > tr > td:nth-child(1) > span.linha",
        "serie": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(1) > div > table:nth-child(2) > tbody > tr > td:nth-child(2) > span.linha",
        "numero": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(1) > div > table:nth-child(2) > tbody > tr > td:nth-child(3) > span.linha",
        "dataEmissao": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(1) > div > table:nth-child(2) > tbody > tr > td:nth-child(4) > span.linha > div",
        "valor": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(1) > div > table:nth-child(2) > tbody > tr > td:nth-child(5) > span.linha",
        "cnpj": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(1) > div > table:nth-child(4) > tbody > tr > td:nth-child(1) > span.linha > div",
        "nome": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(1) > div > table:nth-child(4) > tbody > tr > td:nth-child(2) > span.linha",
        "inscricaoEstadual": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(1) > div > table:nth-child(4) > tbody > tr > td:nth-child(3) > span.linha",
        "uf": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(1) > div > table:nth-child(4) > tbody > tr > td:nth-child(4) > span.linha",
        "processo": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(1) > div > table:nth-child(8) > tbody > tr > td:nth-child(1) > span.linha",
        "processoVer": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(1) > div > table:nth-child(8) > tbody > tr > td:nth-child(2) > span.linha",
        "tipoEmissao": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(1) > div > table:nth-child(8) > tbody > tr > td:nth-child(3) > span.linha",
        "finalidade": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(1) > div > table:nth-child(8) > tbody > tr > td:nth-child(4) > span.linha",
        "natureza": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(1) > div > table:nth-child(9) > tbody > tr > td:nth-child(1) > span.linha",
        "tipoOperacao": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(1) > div > table:nth-child(9) > tbody > tr > td:nth-child(2) > span.linha",
        "formaPagamento": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(1) > div > table:nth-child(9) > tbody > tr > td:nth-child(3) > span.linha",
        "digest": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(1) > div > table:nth-child(9) > tbody > tr > td:nth-child(4) > span.linha",
        "eventos": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(1) > div > table:nth-child(11) > tbody > tr > td:nth-child(1) > span.linha",
        "protocolo": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(1) > div > table:nth-child(11) > tbody > tr > td:nth-child(2) > span.linha",
        "dataAutorizacao": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(1) > div > table:nth-child(11) > tbody > tr > td:nth-child(3) > span.linha > div",
    },
    "emitente": {
        "nome": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(2) > table.textoVerdana7 > tbody > tr:nth-child(1) > td:nth-child(1) > span.linha",
        "nomeFantasia": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(2) > table.textoVerdana7 > tbody > tr:nth-child(1) > td:nth-child(2) > span.linha",
        "cnpj": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(2) > table.textoVerdana7 > tbody > tr:nth-child(2) > td:nth-child(1) > span.linha > div",
        "endereco": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(2) > table.textoVerdana7 > tbody > tr:nth-child(2) > td:nth-child(2) > span.linha",
        "bairro": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(2) > table.textoVerdana7 > tbody > tr:nth-child(3) > td:nth-child(1) > span.linha",
        "cep": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(2) > table.textoVerdana7 > tbody > tr:nth-child(3) > td:nth-child(2) > span.linha > div",
        "cidade": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(2) > table.textoVerdana7 > tbody > tr:nth-child(4) > td > span.linha",
        "telefone": "",
        "uf": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(2) > table.textoVerdana7 > tbody > tr:nth-child(5) > td:nth-child(1) > span.linha",
        "pais": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(2) > table.textoVerdana7 > tbody > tr:nth-child(5) > td:nth-child(2) > span.linha",
        "inscricaoEstadual": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(2) > table.textoVerdana7 > tbody > tr:nth-child(6) > td > span.linha",
        "inscricaoEstadualSubs": "",
        "inscricaoMunicipal": "",
        "municipioICMS": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(2) > table.textoVerdana7 > tbody > tr:nth-child(7) > td > span.linha",
        "cnae": "",
        "codigoRegimeTributario": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(2) > table.textoVerdana7 > tbody > tr:nth-child(8) > td:nth-child(1) > span.linha"
    }, 
    "destinatario": {
        "nome": "",
        "cpf": "",
        "endereco": "",
        "bairro": "",
        "cep": "",
        "cidade": "",
        "telefone": "",
        "uf": "",
        "pais": "",
        "indicadorIE": "",
        "inscricaoEstadual": "",
        "inscricaoSuframa": "",
        "im": "",
        "email": ""
    }, 
    "produtos": {
        "list": "form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(4) > table",
        "item": {
            "descricao": "tbody > tr > td:nth-child(3) > span",
            "quantidade": "tbody > tr > td:nth-child(4) > span",
            "unidade": "tbody > tr > td:nth-child(5) > span",
            "valor": "tbody > tr > td:nth-child(6) > span",
            "codigo": "tbody > tr > td > table:nth-child(1) > tbody > tr:nth-child(1) > td:nth-child(1) > span.linha",
            "codigoNCM": "tbody > tr > td > table:nth-child(1) > tbody > tr:nth-child(1) > td:nth-child(2)",
            "cfop": "tbody > tr > td > table:nth-child(1) > tbody > tr:nth-child(2) > td > span.linha",
            "indicadorComposicao": "tbody > tr > td > table:nth-child(1) > tbody > tr:nth-child(4) > td > span.linha",
            "codigoEANComercial": "tbody > tr > td > table:nth-child(1) > tbody > tr:nth-child(5) > td:nth-child(1) > span.linha",
            "unidadeComercial": "tbody > tr > td > table:nth-child(1) > tbody > tr:nth-child(5) > td:nth-child(2) > span.linha",
            "quantidadeComercial": "tbody > tr > td > table:nth-child(1) > tbody > tr:nth-child(5) > td:nth-child(3) > span.linha",
            "codigoEANTributavel": "tbody > tr > td > table:nth-child(1) > tbody > tr:nth-child(6) > td:nth-child(1) > span.TextoFundoBrancoNegrito",
            "unidadeTributavel": "tbody > tr > td > table:nth-child(1) > tbody > tr:nth-child(6) > td:nth-child(2) > span.linha",
            "quantidadeTributavel": "tbody > tr > td > table:nth-child(1) > tbody > tr:nth-child(6) > td:nth-child(3) > span.linha",
            "valorUnitarioComercial": "tbody > tr > td > table:nth-child(1) > tbody > tr:nth-child(7) > td:nth-child(1) > span.linha",
            "valorUnitarioTributavel": "tbody > tr > td > table:nth-child(1) > tbody > tr:nth-child(7) > td:nth-child(2) > span.linha",
            "valorAproxTributos": "tbody > tr > td > table:nth-child(1) > tbody > tr:nth-child(8) > td > span.linha",
            "origemMercadoria": "tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(1) > td:nth-child(1) > span.linha",
            "tributacaoICMS": "tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(1) > td:nth-child(2) > span.linha",
            "modalidadeICMS": "tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(1) > td:nth-child(3) > span.linha",
            "baseCalculoICMS": "tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(2) > td:nth-child(1) > span.linha",
            "aliquotaICMS": "tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(2) > td:nth-child(2) > span.linha",                
            "valorICMS": "tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(2) > td:nth-child(3) > span.linha",
            "pisCST": "tbody > tr > td > table:nth-child(5) > tbody > tr > td > span.linha",
            "confinsCST": "tbody > tr > td > table:nth-child(7) > tbody > tr > td > span.linha"
        }          
    },
    "impostos": {
        "baseICMS": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(5) > table.textoVerdana7 > tbody > tr:nth-child(1) > td:nth-child(1) > span.linha",
        "icmsValor": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(5) > table.textoVerdana7 > tbody > tr:nth-child(1) > td:nth-child(2) > span.linha",
        "icmsDesonerado": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(5) > table.textoVerdana7 > tbody > tr:nth-child(1) > td:nth-child(3) > span.linha",
        "icmsST": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(5) > table.textoVerdana7 > tbody > tr:nth-child(1) > td:nth-child(4) > span.linha",
        "icmsSubs": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(5) > table.textoVerdana7 > tbody > tr:nth-child(2) > td:nth-child(1) > span.linha",
        "totalProdutos": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(5) > table.textoVerdana7 > tbody > tr:nth-child(2) > td:nth-child(2) > span.linha",
        "totalFrete": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(5) > table.textoVerdana7 > tbody > tr:nth-child(2) > td:nth-child(3) > span.linha",
        "totalSeguro": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(5) > table.textoVerdana7 > tbody > tr:nth-child(2) > td:nth-child(4) > span.linha",
        "despesasAcessorias": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(5) > table.textoVerdana7 > tbody > tr:nth-child(3) > td:nth-child(1) > span.linha",
        "totalIPI": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(5) > table.textoVerdana7 > tbody > tr:nth-child(3) > td:nth-child(2) > span.linha",
        "totalNFE": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(5) > table.textoVerdana7 > tbody > tr:nth-child(3) > td:nth-child(3) > span.linha",
        "totalDescontos": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(5) > table.textoVerdana7 > tbody > tr:nth-child(3) > td:nth-child(4) > span.linha",
        "totalII": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(5) > table.textoVerdana7 > tbody > tr:nth-child(4) > td:nth-child(1) > span.linha",
        "pis": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(5) > table.textoVerdana7 > tbody > tr:nth-child(4) > td:nth-child(2) > span.linha",
        "cofins": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(5) > table.textoVerdana7 > tbody > tr:nth-child(4) > td:nth-child(3) > span.linha",
        "tributosAprox": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(5) > table.textoVerdana7 > tbody > tr:nth-child(4) > td:nth-child(4) > span.linha",
        "icmsFCP": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(5) > table.textoVerdana7 > tbody > tr:nth-child(5) > td:nth-child(1) > span.linha",
        "icmsIntUfDest": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(5) > table.textoVerdana7 > tbody > tr:nth-child(5) > td:nth-child(2) > span.linha",
        "icmsIntUfremet": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(5) > table.textoVerdana7 > tbody > tr:nth-child(5) > td:nth-child(3) > span.linha",
    },
    "transporte": {
        "modalidade": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(6) > table:nth-child(2) > tbody > tr > td > span.linha"
    },
    "cobranca": {
        "forma": "",
        "valor": "",
        "cnpjCred": "",
        "bandeira": "",
        "autorizacao": ""
    },
    "info": {
        "formatoImpressao": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(8) > table:nth-child(2) > tbody > tr > td:nth-child(1) > span.linha",
        "formatoEmissao": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(8) > table:nth-child(2) > tbody > tr > td:nth-child(2) > span.linha",
        "digitoVerificador": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(8) > table:nth-child(2) > tbody > tr > td:nth-child(3) > span.linha",
        "identifacaoAmbiente": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(8) > table:nth-child(3) > tbody > tr > td:nth-child(1) > span.linha",
        "finalidade": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(8) > table:nth-child(3) > tbody > tr > td:nth-child(2) > span.linha",
        "processo": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(8) > table:nth-child(3) > tbody > tr > td:nth-child(3) > span.linha",
        "versao": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(8) > table:nth-child(4) > tbody > tr > td:nth-child(1) > span.linha",
        "entradaContigencia": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(8) > table:nth-child(4) > tbody > tr > td:nth-child(2) > span.linha",
        "justificativa": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(8) > table:nth-child(5) > tbody > tr > td:nth-child(1) > span.linha",
        "descricao": "body > form > div > div.rich-panel-body > table > tbody > tr:nth-child(10) > td > table > tbody > tr:nth-child(2) > td:nth-child(8) > table.textoVerdana7 > tbody > tr:nth-child(1) > td > span.linha"
    },
    "chaveNFe": "",
};