
exports.querySelector = {
    "nfe" : {
        "modelo": "",
        "serie": "",
        "numero": "",
        "dataEmissao": "",
        "valor": "",
        "cnpj": "",
        "nome": "",
        "inscricaoEstadual": "",
        "uf": "",
        "processo": "",
        "processoVer": "",
        "tipoEmissao": "",
        "finalidade": "",
        "natureza": "",
        "tipoOperacao": "",
        "formaPagamento": "",
        "digest": "",
        "eventos": "",
        "protocolo": "",
        "dataAutorizacao": "",
    },
    "emitente": {
        "nome": "",
        "nomeFantasia": "",
        "cnpj": "",
        "endereco": "",
        "bairro": "",
        "cep": "",
        "cidade": "",
        "telefone": "",
        "uf": "",
        "pais": "",
        "inscricaoEstadual": "",
        "inscricaoEstadualSubs": "",
        "inscricaoMunicipal": "",
        "municipioICMS": "",
        "cnae": "",
        "codigoRegimeTributario": ""
    }, 
    "destinatario": {
        "nome": "",
        "cpf": "",
        "endereco": "",
        "bairro": "",
        "cep": "",
        "cidade": "",
        "telefone": "",
        "uf": "",
        "pais": "",
        "indicadorIE": "",
        "inscricaoEstadual": "",
        "inscricaoSuframa": "",
        "im": "",
        "email": ""
    }, 
    "produtos": {
        "list": "",
        "item": {
            "descricao": "",
            "quantidade": "",
            "unidade": "",
            "valor": "",
            "codigo": "",
            "codigoNCM": "",
            "cfop": "",
            "indicadorComposicao": "",
            "codigoEANComercial": "",
            "unidadeComercial": "",
            "quantidadeComercial": "",
            "codigoEANTributavel": "",
            "unidadeTributavel": "",
            "quantidadeTributavel": "",
            "valorUnitarioComercial": "",
            "valorUnitarioTributavel": "",
            "valorAproxTributos": "",
            "origemMercadoria": "",
            "tributacaoICMS": "",
            "modalidadeICMS": "",
            "baseCalculoICMS": "",
            "aliquotaICMS": "",
            "valorICMS": "",
            "pisCST": "",
            "confinsCST": ""
        }          
    },
    "impostos": {
        "baseICMS": "",
        "icmsValor": "",
        "icmsDesonerado": "",
        "icmsST": "",
        "icmsSubs": "",
        "totalProdutos": "",
        "totalFrete": "",
        "totalSeguro": "",
        "despesasAcessorias": "",
        "totalIPI": "",
        "totalNFE": "",
        "totalDescontos": "",
        "totalII": "",
        "pis": "",
        "cofins": "",
        "tributosAprox": "",
        "icmsFCP": "",
        "icmsIntUfDest": "",
        "icmsIntUfremet": "",
    },
    "transporte": {
        "modalidade": ""
    },
    "cobranca": {
        "forma": "",
        "valor": "",
        "cnpjCred": "",
        "bandeira": "",
        "autorizacao": ""
    },
    "info": {
        "formatoImpressao": "",
        "formatoEmissao": "",
        "digitoVerificador": "",
        "identifacaoAmbiente": "",
        "finalidade": "",
        "processo": "",
        "versao": "",
        "entradaContigencia": "",
        "justificativa": "",
        "descricao": ""
    },
    "chaveNFe": "",
};