
exports.querySelector = {
    "chaveNFe": "#textocentral > form > table > tbody > tr:nth-child(1) > td > div.GeralXslt > fieldset > table > tbody > tr > td:nth-child(1) > span",
    "numero": "#textocentral > form > table > tbody > tr:nth-child(1) > td > div.GeralXslt > fieldset > table > tbody > tr > td.fixo-nro-serie > span",
    "versaoXML": "#textocentral > form > table > tbody > tr:nth-child(1) > td > div.GeralXslt > fieldset > table > tbody > tr > td.fixo-versao-xml > span",
    "nfe" : {
        "modelo": "#NFe > fieldset:nth-child(1) > table > tbody > tr > td:nth-child(1) > span",
        "serie": "#NFe > fieldset:nth-child(1) > table > tbody > tr > td:nth-child(2) > span",
        "numero": "#NFe > fieldset:nth-child(1) > table > tbody > tr > td:nth-child(3) > span",
        "dataEmissao": "#NFe > fieldset:nth-child(1) > table > tbody > tr > td:nth-child(4) > span",
        "dataSaida": "#NFe > fieldset:nth-child(1) > table > tbody > tr > td:nth-child(5) > span",
        "valor": "#NFe > fieldset:nth-child(1) > table > tbody > tr > td:nth-child(6) > span",
        "cnpj": "#NFe > fieldset:nth-child(2) > table > tbody > tr > td:nth-child(1) > span",
        "nome": "#NFe > fieldset:nth-child(2) > table > tbody > tr > td.col-2 > span",
        "inscricaoEstadual": "#NFe > fieldset:nth-child(2) > table > tbody > tr > td:nth-child(3) > span",
        "uf": "#NFe > fieldset:nth-child(2) > table > tbody > tr > td.col-10 > span",
        "processo": "#NFe > fieldset:nth-child(3) > table > tbody > tr:nth-child(1) > td:nth-child(1) > span",
        "processoVer": "#NFe > fieldset:nth-child(3) > table > tbody > tr:nth-child(1) > td:nth-child(2) > span",
        "tipoEmissao": "#NFe > fieldset:nth-child(3) > table > tbody > tr:nth-child(1) > td:nth-child(3) > span",
        "finalidade": "#NFe > fieldset:nth-child(3) > table > tbody > tr:nth-child(1) > td:nth-child(4) > span",
        "natureza": "#NFe > fieldset:nth-child(3) > table > tbody > tr:nth-child(2) > td:nth-child(1) > span",
        "tipoOperacao": "#NFe > fieldset:nth-child(3) > table > tbody > tr:nth-child(2) > td:nth-child(2) > span",
        "formaPagamento": "#NFe > fieldset:nth-child(3) > table > tbody > tr:nth-child(2) > td:nth-child(3) > span",
        "digest": "#NFe > fieldset:nth-child(3) > table > tbody > tr:nth-child(2) > td:nth-child(4) > span",
        "eventos": "#NFe > fieldset:nth-child(4) > table > tbody > tr:nth-child(2) > td:nth-child(1) > span",
        "protocolo": "#NFe > fieldset:nth-child(4) > table > tbody > tr:nth-child(2) > td:nth-child(2) > span",
        "dataAutorizacao": "#NFe > fieldset:nth-child(4) > table > tbody > tr:nth-child(2) > td:nth-child(3) > span",
        "dataInclusao": "#NFe > fieldset:nth-child(4) > table > tbody > tr:nth-child(2) > td:nth-child(4) > span"
    },
    "emitente": {
        "nome": "#Emitente > fieldset > table > tbody > tr.col-2 > td:nth-child(1) > span",
        "nomeFantasia": "#Emitente > fieldset > table > tbody > tr.col-2 > td:nth-child(2) > span",
        "cnpj": "#Emitente > fieldset > table > tbody > tr:nth-child(2) > td:nth-child(1) > span",
        "endereco": "#Emitente > fieldset > table > tbody > tr:nth-child(2) > td:nth-child(2) > span",
        "bairro": "#Emitente > fieldset > table > tbody > tr:nth-child(3) > td:nth-child(1) > span",
        "cep": "#Emitente > fieldset > table > tbody > tr:nth-child(3) > td:nth-child(2) > span",
        "cidade": "#Emitente > fieldset > table > tbody > tr:nth-child(4) > td:nth-child(1) > span",
        "telefone": "#Emitente > fieldset > table > tbody > tr:nth-child(4) > td:nth-child(2) > span",
        "uf": "#Emitente > fieldset > table > tbody > tr:nth-child(5) > td:nth-child(1) > span",
        "pais": "#Emitente > fieldset > table > tbody > tr:nth-child(5) > td:nth-child(2) > span",
        "inscricaoEstadual": "#Emitente > fieldset > table > tbody > tr:nth-child(6) > td:nth-child(1) > span",
        "inscricaoEstadualSubs": "#Emitente > fieldset > table > tbody > tr:nth-child(6) > td:nth-child(2) > span",
        "inscricaoMunicipal": "#Emitente > fieldset > table > tbody > tr:nth-child(7) > td:nth-child(1) > span",
        "municipioICMS": "#Emitente > fieldset > table > tbody > tr:nth-child(7) > td:nth-child(2) > span",
        "cnae": "#Emitente > fieldset > table > tbody > tr:nth-child(8) > td:nth-child(1) > span",
        "codigoRegimeTributario": "#Emitente > fieldset > table > tbody > tr:nth-child(8) > td:nth-child(2) > span"
    }, 
    "destinatario": {
        "nome": "#DestRem > fieldset > table > tbody > tr:nth-child(1) > td > span",
        "cnpj_cpf": "#DestRem > fieldset > table > tbody > tr:nth-child(2) > td:nth-child(1) > span",
        "endereco": "#DestRem > fieldset > table > tbody > tr:nth-child(2) > td:nth-child(2) > span",
        "bairro": "#DestRem > fieldset > table > tbody > tr:nth-child(3) > td:nth-child(1) > span",
        "cep": "#DestRem > fieldset > table > tbody > tr:nth-child(3) > td:nth-child(2) > span",
        "cidade": "#DestRem > fieldset > table > tbody > tr:nth-child(4) > td:nth-child(1) > span",
        "telefone": "#DestRem > fieldset > table > tbody > tr:nth-child(4) > td:nth-child(2) > span",
        "uf": "#DestRem > fieldset > table > tbody > tr:nth-child(5) > td:nth-child(1) > span",
        "pais": "#DestRem > fieldset > table > tbody > tr:nth-child(5) > td:nth-child(2) > span",
        "indicadorIE": "#DestRem > fieldset > table > tbody > tr:nth-child(6) > td:nth-child(1) > span",
        "inscricaoEstadual": "#DestRem > fieldset > table > tbody > tr:nth-child(6) > td:nth-child(2) > span",
        "inscricaoSuframa": "#DestRem > fieldset > table > tbody > tr:nth-child(6) > td:nth-child(3) > span",
        "im": "#DestRem > fieldset > table > tbody > tr:nth-child(7) > td:nth-child(1) > span",
        "email": "#DestRem > fieldset > table > tbody > tr:nth-child(7) > td:nth-child(2) > span"
    }, 
    "produtos": {
        "list": "#Prod > fieldset > div > table.box",
        "item": {
            "descricao": "tbody > tr > td.fixo-prod-serv-descricao > span",
            "quantidade": "tbody > tr > td.fixo-prod-serv-qtd > span",
            "unidade": "tbody > tr > td.fixo-prod-serv-uc > span",
            "valor": "tbody > tr > td.fixo-prod-serv-vb > span",
            "codigo": "tbody > tr > td > table:nth-child(1) > tbody > tr.col-4 > td:nth-child(1) > span",
            "codigoNCM": "tbody > tr > td > table:nth-child(1) > tbody > tr.col-4 > td:nth-child(2) > span",
            "cest": "tbody > tr > td > table:nth-child(1) > tbody > tr.col-4 > td:nth-child(3) > span",
            "ex_tipi": "tbody > tr > td > table:nth-child(1) > tbody > tr:nth-child(2) > td:nth-child(1) > span",
            "cfop": "tbody > tr > td > table:nth-child(1) > tbody > tr:nth-child(2) > td:nth-child(2) > span",
            "despesas": "tbody > tr > td > table:nth-child(1) > tbody > tr:nth-child(2) > td:nth-child(3) > span",
            "desconto": "tbody > tr > td > table:nth-child(1) > tbody > tr:nth-child(3) > td:nth-child(1) > span",
            "freteTotal": "tbody > tr > td > table:nth-child(1) > tbody > tr:nth-child(3) > td:nth-child(2) > span",
            "seguro": "tbody > tr > td > table:nth-child(1) > tbody > tr:nth-child(3) > td:nth-child(3) > span",
            "indicadorComposicao": "tbody > tr > td > table:nth-child(3) > tbody > tr.col-12 > td > span",
            "codigoEANComercial": "tbody > tr > td > table:nth-child(3) > tbody > tr.col-3 > td:nth-child(1) > span",
            "unidadeComercial": "tbody > tr > td > table:nth-child(3) > tbody > tr.col-3 > td:nth-child(2) > span",
            "quantidadeComercial": "tbody > tr > td > table:nth-child(3) > tbody > tr.col-3 > td:nth-child(3) > span",
            "codigoEANTributavel": "tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(3) > td:nth-child(1) > span",
            "unidadeTributavel": "tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(3) > td:nth-child(2) > span",
            "quantidadeTributavel": "tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(3) > td:nth-child(3) > span",
            "valorUnitarioComercial": "tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(4) > td:nth-child(1) > span",
            "valorUnitarioTributavel": "tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(4) > td:nth-child(2) > span",
            "numeroPedido": "tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(5) > td:nth-child(1) > span",
            "itemPedido": "tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(5) > td:nth-child(2) > span",
            "valorAproxTributos": "tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(5) > td:nth-child(3) > span",
            "numeroFCI": "tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(6) > td > span",
            "origemMercadoria": "tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(7) > td > fieldset > table > tbody > tr:nth-child(1) > td:nth-child(1) > span",
            "tributacaoICMS": "tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(7) > td > fieldset > table > tbody > tr:nth-child(1) > td:nth-child(2) > span",
            "modalidadeICMS": "tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(7) > td > fieldset > table > tbody > tr:nth-child(1) > td:nth-child(3) > span",
            "baseCalculoICMS": "tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(7) > td > fieldset > table > tbody > tr:nth-child(2) > td:nth-child(1) > span",
            "aliquotaICMS": "tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(7) > td > fieldset > table > tbody > tr:nth-child(2) > td:nth-child(2) > span",
            "valorICMS": "tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(7) > td > fieldset > table > tbody > tr:nth-child(2) > td:nth-child(3) > span",
            "pisCST": "tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(8) > td > fieldset > div > table > tbody > tr:nth-child(1) > td > span",
            "pisBaseCalculo": "tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(8) > td > fieldset > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > span",
            "pisAliquota": "tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(8) > td > fieldset > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > span",
            "pisValor": "tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(8) > td > fieldset > div > table > tbody > tr:nth-child(2) > td:nth-child(3) > span",
            "confinsCST": "tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(10) > td > fieldset > div > table > tbody > tr:nth-child(1) > td > span",
            "confinsBaseCalculo": "tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(10) > td > fieldset > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > span",
            "confinsAliquota": "tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(10) > td > fieldset > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > span",
            "confinsValor": "tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(10) > td > fieldset > div > table > tbody > tr:nth-child(2) > td:nth-child(3) > span"
        }          
    },
    "impostos": {
        "baseICMS": "#Totais > fieldset > fieldset > table > tbody > tr.col-4 > td:nth-child(1) > span",
        "icmsValor": "#Totais > fieldset > fieldset > table > tbody > tr.col-4 > td:nth-child(2) > span",
        "icmsDesonerado": "#Totais > fieldset > fieldset > table > tbody > tr.col-4 > td:nth-child(3) > span",
        "icmsST": "#Totais > fieldset > fieldset > table > tbody > tr.col-4 > td:nth-child(4) > span",
        "icmsSubs": "#Totais > fieldset > fieldset > table > tbody > tr:nth-child(2) > td:nth-child(1) > span",
        "totalProdutos": "#Totais > fieldset > fieldset > table > tbody > tr:nth-child(2) > td:nth-child(2) > span",
        "totalFrete": "#Totais > fieldset > fieldset > table > tbody > tr:nth-child(2) > td:nth-child(3) > span",
        "totalSeguro": "#Totais > fieldset > fieldset > table > tbody > tr:nth-child(2) > td:nth-child(4) > span",
        "despesasAcessorias": "#Totais > fieldset > fieldset > table > tbody > tr:nth-child(3) > td:nth-child(1) > span",
        "totalIPI": "#Totais > fieldset > fieldset > table > tbody > tr:nth-child(3) > td:nth-child(2) > span",
        "totalNFE": "#Totais > fieldset > fieldset > table > tbody > tr:nth-child(3) > td:nth-child(3) > span",
        "totalDescontos": "#Totais > fieldset > fieldset > table > tbody > tr:nth-child(3) > td:nth-child(4) > span",
        "totalII": "#Totais > fieldset > fieldset > table > tbody > tr:nth-child(4) > td:nth-child(1) > span",
        "pis": "#Totais > fieldset > fieldset > table > tbody > tr:nth-child(4) > td:nth-child(2) > span",
        "cofins": "#Totais > fieldset > fieldset > table > tbody > tr:nth-child(4) > td:nth-child(3) > span",
        "tributosAprox": "#Totais > fieldset > fieldset > table > tbody > tr:nth-child(4) > td:nth-child(4) > span",
        "icmsFCP": "#Totais > fieldset > fieldset > table > tbody > tr:nth-child(5) > td:nth-child(1) > span",
        "icmsIntUfDest": "#Totais > fieldset > fieldset > table > tbody > tr:nth-child(5) > td:nth-child(2) > span",
        "icmsIntUfremet": "#Totais > fieldset > fieldset > table > tbody > tr:nth-child(5) > td:nth-child(3) > span",
    },
    "transporte": {
        "modalidade": "#Transporte > fieldset > table > tbody > tr > td > span"
    },
    "cobranca": {
        "forma": "#Cobranca > fieldset > fieldset > table > tbody > tr:nth-child(2) > td:nth-child(1) > span",
        "valor": "#Cobranca > fieldset > fieldset > table > tbody > tr:nth-child(2) > td:nth-child(2) > span",
        "cnpjCred": "#Cobranca > fieldset > fieldset > table > tbody > tr:nth-child(2) > td:nth-child(4) > span",
        "bandeira": "#Cobranca > fieldset > fieldset > table > tbody > tr:nth-child(2) > td:nth-child(5) > span",
        "autorizacao": "#Cobranca > fieldset > fieldset > table > tbody > tr:nth-child(2) > td:nth-child(6) > span",
        "tipoIntegracao": "#Cobranca > fieldset > fieldset > table > tbody > tr:nth-child(2) > td:nth-child(3) > span"
    },
    "info": {
        "formatoImpressao": "#Inf > fieldset > table > tbody > tr > td > span",
        "qrcode": "#Inf > fieldset > fieldset:nth-child(5) > table > tbody > tr > td > span",
        "descricao": "#Inf > fieldset > fieldset:nth-child(4) > table > tbody > tr > td > span > div"
    }    
};