version: 2
jobs:
  build:
    working_directory: ~/mimercato-nfce
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: circleci/node:7.10
    machine:
      pre:
        - sudo curl --output /usr/local/bin/phantomjs https://s3.amazonaws.com/circle-downloads/phantomjs-2.1.1
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      #- restore_cache:
      #    key: dependency-cache-{{ checksum "package.json" }}     
      - run:
          name: Install phantomjs
          command: |
            sudo apt-get install build-essential
      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version
            phantomjs --version
      - run:
          name: Install npm
          command: 'npm install'
      #- save_cache:
      #    key: dependency-cache-{{ checksum "package.json" }}
      #    paths:
      #      - node_modules
  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Test
          command: 'npm test'
      - run:
          name: Generate code coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
              
notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/acd950313416a46611a2
